# Site settings
title: Zend Framework 2 Translations Editor
email: alemaire@circlical.com
description: > # this means to ignore newlines until "baseurl:"
  Tired of pulling your hair over PoEdit?  Using Twig and PHP?
  Welcome to the promised land.  Set this module up to supercharge
  your translations today.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: Alex
email: alemaire@circlical.com
facebook_username: Saeven
twitter_username: Saeven
github_username: Saeven
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright:

# API settings
google_api_key:

# Build settings
markdown: kramdown